import { Domain } from './types';

export const DOMAINS: Domain[] = [
  {
    id: 1,
    name: 'TAMAS',
    subtitle: 'Inert Domain',
    description: 'Awareness dormant. Experience without agency.',
    color: 'text-slate-500',
    states: [
      { id: 1, name: 'Mineral Stasis', description: 'Complete dormancy of awareness.' },
      { id: 2, name: 'Elemental Pressure', description: 'Existence defined by external force.' },
      { id: 3, name: 'Deep-Earth Stillness', description: 'Profound, unmoving silence.' },
      { id: 4, name: 'Crystalline Repetition', description: 'Ordered, repetitive structural existence.' },
      { id: 5, name: 'Thermal Inertia', description: 'Reactive only to temperature states.' },
      { id: 6, name: 'Magnetic Passivity', description: 'Aligned solely by external fields.' },
      { id: 7, name: 'Structural Endurance', description: 'Bearing weight without collapsing.' },
      { id: 8, name: 'Geological Time', description: 'Awareness expanded to eons.' },
      { id: 9, name: 'Static Density', description: 'Heavy, compressed state of being.' },
      { id: 10, name: 'Absolute Dependency', description: 'Cannot exist without a host context.' },
      { id: 11, name: 'Non-Reactive Existence', description: 'Stimuli do not provoke response.' },
      { id: 12, name: 'Pre-Life Memory', description: 'The container for potential biology.' },
    ],
  },
  {
    id: 2,
    name: 'INSTINCT',
    subtitle: 'Survival Domain',
    description: 'Life begins reacting. Fear, food, territory.',
    color: 'text-emerald-600',
    states: [
      { id: 13, name: 'Aquatic Reflex', description: 'Pure reaction to fluid dynamics.' },
      { id: 14, name: 'Reptilian Vigilance', description: 'Cold, unblinking observation.' },
      { id: 15, name: 'Amphibian Anxiety', description: 'The stress of dual environments.' },
      { id: 16, name: 'Nocturnal Fear-Loop', description: 'Awareness heightened by darkness.' },
      { id: 17, name: 'Predator Dominance', description: 'Identity derived from the hunt.' },
      { id: 18, name: 'Prey Alertness', description: 'Identity derived from evasion.' },
      { id: 19, name: 'Herd Conformity', description: 'Safety in identical replication.' },
      { id: 20, name: 'Territorial Obsession', description: 'Self defined by boundary lines.' },
      { id: 21, name: 'Hunger Intelligence', description: 'Cognition purely for consumption.' },
      { id: 22, name: 'Fight-or-Flight', description: 'Binaristic stress response mode.' },
      { id: 23, name: 'Sensory Overdrive', description: 'Overwhelmed by raw input.' },
      { id: 24, name: 'Survival Mastery', description: 'The apex of physical preservation.' },
    ],
  },
  {
    id: 3,
    name: 'EMOTION',
    subtitle: 'Bonding Domain',
    description: 'Attachment enters. Love, loss, connection.',
    color: 'text-rose-500',
    states: [
      { id: 25, name: 'Maternal Bonding', description: 'The first break from solipsism.' },
      { id: 26, name: 'Pack Loyalty', description: 'Identity merged with the group.' },
      { id: 27, name: 'Sexual Emergence', description: 'Drive for biological union.' },
      { id: 28, name: 'Jealousy Loop', description: 'Fear of losing the attached object.' },
      { id: 29, name: 'Protection Instinct', description: 'Violence justified by love.' },
      { id: 30, name: 'Loss Trauma', description: 'Awareness shaped by absence.' },
      { id: 31, name: 'Playfulness', description: 'Learning through mock-reality.' },
      { id: 32, name: 'Social Ranking', description: 'Self-worth via comparison.' },
      { id: 33, name: 'Empathy Flicker', description: 'Briefly feeling another\'s state.' },
      { id: 34, name: 'Emotional Storage', description: 'Hoarding feelings as memories.' },
      { id: 35, name: 'Dependence Addiction', description: 'Inability to self-regulate.' },
      { id: 36, name: 'Attachment Exhaustion', description: 'Burnout from feeling too much.' },
    ],
  },
  {
    id: 4,
    name: 'ACTION',
    subtitle: 'Power Domain',
    description: 'Ego awakens. Karma through action.',
    color: 'text-orange-500',
    states: [
      { id: 37, name: 'Tool-User Mindset', description: 'Leveraging environment for will.' },
      { id: 38, name: 'Builder Impulse', description: 'Constructing order from chaos.' },
      { id: 39, name: 'Warrior Assertion', description: 'Imposing will through force.' },
      { id: 40, name: 'Competitive Drive', description: 'Defining self by winning.' },
      { id: 41, name: 'Expansion Hunger', description: 'The need for "more" territory.' },
      { id: 42, name: 'Leadership Intoxication', description: 'Addiction to being followed.' },
      { id: 43, name: 'Control Obsession', description: 'Micromanaging entropy.' },
      { id: 44, name: 'Dominance Fatigue', description: 'The tiredness of holding power.' },
      { id: 45, name: 'Responsibility Burden', description: 'Weight of collective outcome.' },
      { id: 46, name: 'Consequence Awareness', description: 'Realizing cause and effect.' },
      { id: 47, name: 'Ethical Conflict', description: 'Action vs. Morality tension.' },
      { id: 48, name: 'Power Renunciation', description: 'Voluntarily stepping down.' },
    ],
  },
  {
    id: 5,
    name: 'COGNITION',
    subtitle: 'Identity Domain',
    description: 'The "I am" crystallizes. Mind observing itself.',
    color: 'text-blue-500',
    states: [
      { id: 49, name: 'Self-Recognition', description: 'I am separate from the world.' },
      { id: 50, name: 'Language Identity', description: 'I am the words I speak.' },
      { id: 51, name: 'Social Mask', description: 'Curating the avatar for others.' },
      { id: 52, name: 'Status Anxiety', description: 'Fear of rank degradation.' },
      { id: 53, name: 'Ideology Attachment', description: 'I am my belief system.' },
      { id: 54, name: 'Belief Rigidity', description: 'Refusal to update the model.' },
      { id: 55, name: 'Intellectual Pride', description: 'Arrogance of the database.' },
      { id: 56, name: 'Doubt Collapse', description: 'The model begins to fail.' },
      { id: 57, name: 'Existential Questioning', description: 'Why is the system running?' },
      { id: 58, name: 'Observer Awakening', description: 'Who is watching the mind?' },
      { id: 59, name: 'Ego Fracture', description: 'The mask cracks open.' },
      { id: 60, name: 'Identity Surrender', description: 'Giving up the need to be "Someone".' },
    ],
  },
  {
    id: 6,
    name: 'WISDOM',
    subtitle: 'Detachment Domain',
    description: 'Seeing without clinging. Freedom within form.',
    color: 'text-violet-400',
    states: [
      { id: 61, name: 'Witness Mode', description: 'Pure observation, zero interference.' },
      { id: 62, name: 'Desire Thinning', description: 'Cravings lose their magnetic pull.' },
      { id: 63, name: 'Time Relativity', description: 'Past and future dissolve.' },
      { id: 64, name: 'Impermanence Clarity', description: 'Deep acceptance of entropy.' },
      { id: 65, name: 'Clean Compassion', description: 'Caring without attachment.' },
      { id: 66, name: 'Karma Literacy', description: 'Reading the code of cause/effect.' },
      { id: 67, name: 'Silence Intelligence', description: 'Understanding without words.' },
      { id: 68, name: 'Identity-less Service', description: 'Acting without a "doer".' },
      { id: 69, name: 'Non-Dual Glimpse', description: 'Subject and object merge briefly.' },
      { id: 70, name: 'Fear Dissolution', description: 'The root program is deleted.' },
      { id: 71, name: 'Death Familiarity', description: 'Viewing end-state as transition.' },
      { id: 72, name: 'Voluntary Simplicity', description: 'Optimizing for minimal drag.' },
    ],
  },
  {
    id: 7,
    name: 'LIBERATED',
    subtitle: 'Transitional Domain',
    description: 'Exit states. Choice beyond compulsion.',
    color: 'text-amber-400',
    states: [
      { id: 73, name: 'Life-as-Play', description: 'The universe as a sandbox.' },
      { id: 74, name: 'Karma Burn-Down', description: 'Resolving remaining threads.' },
      { id: 75, name: 'Non-Reactive Living', description: 'Action without reaction.' },
      { id: 76, name: 'Birth-Choice Awareness', description: 'Choosing the next login.' },
      { id: 77, name: 'Teacher State', description: 'Broadcasting the exit code.' },
      { id: 78, name: 'Silent Influencer', description: 'Shifting the field by presence.' },
      { id: 79, name: 'Compassionate Return', description: 'Refusal to leave until others do.' },
      { id: 80, name: 'Individual Dissolution', description: 'The drop joins the ocean.' },
      { id: 81, name: 'Collective Merge', description: 'We > I.' },
      { id: 82, name: 'Witness Beyond Body', description: 'Consciousness independent of hardware.' },
      { id: 83, name: 'Threshold Consciousness', description: 'Standing at the final door.' },
      { id: 84, name: 'Moksha / Reset', description: 'System Exit. Game Over. Freedom.' },
    ],
  },
];
